use std::path::{Path, PathBuf};
use std::os::unix::fs::PermissionsExt;
use anyhow::{Context, Result};

use super::layout::InstanceLayout;

pub struct Launcher;

impl Launcher {
    pub fn generate(alias: &str, layout: &InstanceLayout, binary_name: &str) -> String {
        let instance_dir = layout.root.to_string_lossy();
        format!(
            r#"#!/usr/bin/env bash
# Warren launcher — {alias}
# Generated by warren {version}

set -euo pipefail

WARREN_INSTANCE_DIR="{instance_dir}"

export HOME="${{WARREN_INSTANCE_DIR}}/home"
export XDG_CONFIG_HOME="${{WARREN_INSTANCE_DIR}}/config"
export XDG_CACHE_HOME="${{WARREN_INSTANCE_DIR}}/cache"
export XDG_DATA_HOME="${{WARREN_INSTANCE_DIR}}/data"
export XDG_STATE_HOME="${{WARREN_INSTANCE_DIR}}/state"
export XDG_RUNTIME_DIR="${{WARREN_INSTANCE_DIR}}/runtime"
export TMPDIR="${{WARREN_INSTANCE_DIR}}/tmp"
export WARREN_INSTANCE="{alias}"
export WARREN_INSTANCE_DIR

exec "${{WARREN_INSTANCE_DIR}}/bin/{binary_name}" "$@"
"#,
            alias = alias,
            version = env!("CARGO_PKG_VERSION"),
            instance_dir = instance_dir,
            binary_name = binary_name,
        )
    }

    pub fn write(layout: &InstanceLayout, content: &str) -> Result<PathBuf> {
        let launcher_path = layout.launcher_path();
        std::fs::write(&launcher_path, content)
            .with_context(|| format!("failed to write launcher to {}", launcher_path.display()))?;
        let perms = std::fs::Permissions::from_mode(0o755);
        std::fs::set_permissions(&launcher_path, perms)
            .with_context(|| format!("failed to set permissions on {}", launcher_path.display()))?;
        tracing::debug!(path = %launcher_path.display(), "wrote launcher script");
        Ok(launcher_path)
    }

    pub fn install(layout: &InstanceLayout, bin_dir: &Path, alias: &str) -> Result<PathBuf> {
        std::fs::create_dir_all(bin_dir)
            .with_context(|| format!("failed to create bin directory {}", bin_dir.display()))?;
        let target = bin_dir.join(alias);
        let launcher = layout.launcher_path();
        if target.exists() || target.symlink_metadata().is_ok() {
            std::fs::remove_file(&target)
                .with_context(|| format!("failed to remove existing launcher at {}", target.display()))?;
        }
        match std::os::unix::fs::symlink(&launcher, &target) {
            Ok(()) => {
                tracing::debug!(src = %launcher.display(), dst = %target.display(), "symlinked launcher");
            }
            Err(e) => {
                tracing::warn!(error = %e, "symlink failed, falling back to copy");
                std::fs::copy(&launcher, &target)
                    .with_context(|| format!("failed to copy launcher to {}", target.display()))?;
                let perms = std::fs::Permissions::from_mode(0o755);
                std::fs::set_permissions(&target, perms)?;
            }
        }
        Ok(target)
    }

    pub fn uninstall(bin_dir: &Path, alias: &str) -> Result<()> {
        let target = bin_dir.join(alias);
        if target.exists() || target.symlink_metadata().is_ok() {
            std::fs::remove_file(&target)
                .with_context(|| format!("failed to remove launcher at {}", target.display()))?;
            tracing::debug!(path = %target.display(), "removed launcher");
        }
        Ok(())
    }
}
