name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare asset
        run: |
          mkdir -p release_dir
          cp target/x86_64-unknown-linux-gnu/release/warren release_dir/
          cd release_dir
          tar -czvf warren-linux-x86_64.tar.gz warren
          mv warren-linux-x86_64.tar.gz ../

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: warren-linux-x86_64.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.RUST_TOKEN }}
